/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ComidasBaratasRouteImport } from './routes/comidas-baratas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecetaIdRouteImport } from './routes/receta.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ComidasBaratasRoute = ComidasBaratasRouteImport.update({
  id: '/comidas-baratas',
  path: '/comidas-baratas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetaIdRoute = RecetaIdRouteImport.update({
  id: '/receta/$id',
  path: '/receta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comidas-baratas': typeof ComidasBaratasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receta/$id': typeof RecetaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comidas-baratas': typeof ComidasBaratasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receta/$id': typeof RecetaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comidas-baratas': typeof ComidasBaratasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receta/$id': typeof RecetaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comidas-baratas' | '/sitemap.xml' | '/receta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comidas-baratas' | '/sitemap.xml' | '/receta/$id'
  id: '__root__' | '/' | '/comidas-baratas' | '/sitemap.xml' | '/receta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComidasBaratasRoute: typeof ComidasBaratasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RecetaIdRoute: typeof RecetaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comidas-baratas': {
      id: '/comidas-baratas'
      path: '/comidas-baratas'
      fullPath: '/comidas-baratas'
      preLoaderRoute: typeof ComidasBaratasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receta/$id': {
      id: '/receta/$id'
      path: '/receta/$id'
      fullPath: '/receta/$id'
      preLoaderRoute: typeof RecetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComidasBaratasRoute: ComidasBaratasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RecetaIdRoute: RecetaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
